"""create reports table

Revision ID: 0c5b070305e4
Revises: bfbd1db9fd54
Create Date: 2021-06-12 22:03:32.695093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5b070305e4'
down_revision = 'bfbd1db9fd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('coin_stats', sa.Boolean(), nullable=True),
    sa.Column('social_metrics', sa.Boolean(), nullable=True),
    sa.Column('github_metrics', sa.Boolean(), nullable=True),
    sa.Column('trending', sa.Boolean(), nullable=True),
    sa.Column('overall_metrics', sa.Boolean(), nullable=True),
    sa.Column('daily_report', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_report')
    # ### end Alembic commands ###
