"""Update daily_coin_stats to include new fields

Revision ID: a6780d706762
Revises: 
Create Date: 2021-05-07 18:31:27.452581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6780d706762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_coin_stats', sa.Column('ath_percent_change', sa.Float(), nullable=True))
    op.add_column('daily_coin_stats', sa.Column('atl_percent_change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_coin_stats', 'atl_percent_change')
    op.drop_column('daily_coin_stats', 'ath_percent_change')
    # ### end Alembic commands ###
