"""cahnge circulating supply from integer to float

Revision ID: b1d2f8bc258d
Revises: 7b47998b707e
Create Date: 2021-05-15 11:54:36.266861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d2f8bc258d'
down_revision = '7b47998b707e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_coin_stats', 'circulating_supply',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='circulating_supply::double precision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_coin_stats', 'circulating_supply',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
