"""change market dominance from Float to Numeric

Revision ID: c9c24c37dce4
Revises: e00b8f45a279
Create Date: 2021-05-20 10:18:34.486651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9c24c37dce4'
down_revision = 'e00b8f45a279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_coin_stats', 'market_dominance',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_coin_stats', 'market_dominance',
               existing_type=sa.Numeric(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
