"""add commits field to daily_github_metrics model

Revision ID: d83a4d7f1e6b
Revises: a6780d706762
Create Date: 2021-05-09 10:31:04.598843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83a4d7f1e6b'
down_revision = 'a6780d706762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_github_metrics', sa.Column('commits', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_github_metrics', 'commits')
    # ### end Alembic commands ###
