"""create a columb to save price percentage change

Revision ID: e00b8f45a279
Revises: b1d2f8bc258d
Create Date: 2021-05-15 12:10:44.733797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00b8f45a279'
down_revision = 'b1d2f8bc258d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_coin_stats', sa.Column('price_percentage_change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_coin_stats', 'price_percentage_change')
    # ### end Alembic commands ###
