"""use numeric field type for price field in trending model

Revision ID: e5837d215cca
Revises: c9dc32d46a5e
Create Date: 2021-05-11 04:09:05.040342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5837d215cca'
down_revision = 'c9dc32d46a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trending', 'volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('trending', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trending', 'price',
               existing_type=sa.Numeric(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('trending', 'volume',
               existing_type=sa.Numeric(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
